services:
  - type: web
    name: messenger
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: messenger-db
          property: connectionString
      - key: GOOGLE_DRIVE_FOLDER_ID
        value: 1D_Dm6hB1o_Ml4cZlIG6tdUVG61we_50a # замени на реальный ID
      - key: GOOGLE_CREDENTIALS
        value: "{\"type\":\"service_account\",\"project_id\":\"ksm-direct-database\",\"private_key_id\":\"36ae463412e3bfeb20ce28857a92f4006b513f63\",\"private_key\":\"-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCyZh8bkGLIWBrh\\nkO/0rH37FO1RSXpiOdJj9dW9xgVOJ9mV14ByvudkaDOQ2Xhuri0FLRunWguBYfZy\\npWKBZjJ2gxB0w1Ygk91VZq/7nmBpsDGvstP3QaVAGZwuIM+KkVG77n26LKTweiDX\\nAGrLrfhh6ZI96rG65LYPKppFanmfgiXrmXQJYNRDbfK01VLdzXoOMka6n11tkyrJ\\n1gypYwCMS1V5TcQbIvSjKkSml0AoOZAjuONEayFju0RzhNQTB3PJ+GlJcGveoRXG\\nVj8s40ygUnYHsHg/c1IaB9chlKz45ohIoqtCZ9cnKhzOHbduyFC9zyTat2aHfeuF\\nfWICCpoXAgMBAAECggEAVwJv0aXOSCCQm8tw/UjT+Q3v4WGRCy9gadiQ8woNtFzD\\nRs3gnBZ4DQS1gcRPdMwGsSua/ThxvBzncmsvbCVIH301HX3YF/OGVAzNcE+Cfoms\\n8iCqOUIPMwBKqETgdJkD4EElmRQFLjSip7pQXB7xse+VoBVDsf+yvBrvO0P/Jcgn\\n6PZdBzi8oqnFy/T8k7ASt+ERj/Baevzq3bCiBaJ7SO0Yh1Klf1lzbkKohx6Ae1cX\\nXS3W6qoSkEWrAN/Ua9FGUqh1e4ppt0EkADO1vGMdRnkF/S2FypDJ4XXt2F6eeZqb\\n3QuXmv6/WEtkDWBA9z6ExBfCL4eYKwqIPzMmri8BgQKBgQDa4SzFzmJ4TRdqkzgS\\nD5GSQAcsFN6w3hTtahnAzlIYY+/qmlIRtKbzqTZ/rS7t5SowjO3CMmrXooLYwDA4\\nvWjyESdpX/TnAx+3NmJGy755EKAxO1s0v0hk4tz/tQHOjcG3fFiFzaSpUEgQkA6M\\nBy+PBhzBrEjPwCW2fbYfB5YQcQKBgQDQp3JuXrMbkxplfIrUAXyI8m9UTeT7ynnu\\nm8ZsCKY4MDwjfcreDKnr1bwZujVKhsmkLRCdVYZx+SdJh5xTOWG/zu5X8nQTmMBb\\ns0qEHrG9WP4P8/9iIFv4YMif4yKn5DMHIkdanX5Qmy2N0nKfaURHEAxLWi3QhMCF\\nrupLQ9YXBwKBgFycvmcMBppEdE4B8M2jjMLHGMHMKtXHgi9an373TcFIN/GaTnNz\\nbtjWllq7monKV2mnl8p9rruC5b50w3KeolMacwShN2yv47GP71FpUDTFliJ+rP7K\\nmQUnAL+phRQy4u6STJqBAtUpRPTNH3qcZ8EqouxHy58r/EkVNAQ5H4PhAoGBAMvZ\\njDbAVoQuJ6/XCVsvSJgTIyleIMTOgGnZzvVlTd+/YEHceAKQpMI/wtHv1njFTuMT\\nFBRipkNbhEKWNugoO5PFe554xWcP6X6tn7OMuWGgPDchzvPzYWc8R0XOBuG4VRI3\\nLzccf3gI42yXmlyb35T93MURiYka6WyyAz0dPWCpAoGAb7X7u5blHij0D/jZKb9E\\n9sAA/ALmRrU9ZQLuOS3y5D8pmCIze1ZOq+1scPBr+BE4BlNjrgC0abPbm25ylH4U\\nvaJvSmSE6yYFByqtXZ9Bxg4d+mwe+5y/ABCSEoymFVA3Xrb2TXXWZ9GYYZE+4hli\\nvnMDrExCwywOEfjpxTvjjJo=\\n-----END PRIVATE KEY-----\\n\",\"client_email\":\"ksm4k-db@ksm-direct-database.iam.gserviceaccount.com\",\"client_id\":\"101861688393372655237\",\"auth_uri\":\"https://accounts.google.com/o/oauth2/auth\",\"token_uri\":\"https://oauth2.googleapis.com/token\",\"auth_provider_x509_cert_url\":\"https://www.googleapis.com/oauth2/v1/certs\",\"client_x509_cert_url\":\"https://www.googleapis.com/robot/v1/metadata/x509/ksm4k-db%40ksm-direct-database.iam.gserviceaccount.com\",\"universe_domain\":\"googleapis.com\"}"

databases:
  - name: messenger-db
    databaseName: messenger
    plan: free
